version: '3'
services:

  #PHP Service
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
            - ./:/var/www
    restart: unless-stopped
    tty: true
    networks:
      - laravel-network

  #Web Server(NGINX)
  web:
    container_name: laravel_web
    build:
        context: ./
        dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - 8001:80
    networks:
      - laravel-network

  #MySQL Service
  db:
    container_name: laravel_db
    image: mariadb
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - ./dbdata:/var/lib/mysql/
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

  phpmyadmin:
    container_name: laravel_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=laravel_db
      - PMA_USER=root
      - PMA_PASSWORD=laravel
      - MAX_EXECUTION_TIME=3600
      - UPLOAD_LIMIT=512M
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge
